server:
  listen: "0.0.0.0:${PORT}"
  #
  # CORS (Cross Origin Resource Sharing)
  #
  cors:
    # List of accepted origins
    origins:
      - https://studio.apollographql.com

    allow_headers: [Content-Type, Authorization]
headers:
  subgraphs:
    accounts:
      - propagate:
          named: "Authorization"
