server:
  # Set to 0.0.0.0 to circumvent Heroku error
  listen: "0.0.0.0:${PORT}"
  # Don't see any instruction to introspect
  # introspection: false
  # Turn off landing page
  # landing_page: false
  #
  # CORS (Cross Origin Resource Sharing)
  #
  cors:
    # List of accepted origins
    origins:
      - https://studio.apollographql.com

    allow_headers: [Content-Type, Authorization]
override_subgraph_url:
  locations: "http://localhost:4001"
  reviews: "http://localhost:4002"
